### ISSUE TITLE
ng-clip not working on mobile phone

### ISSUE THREAD

**Issue by sourav86** [asafdav/ng-clip#61]
I have applied ng-clip in my project it is working fine in desktop but not working on mobile devices

**Comment by asafdav** [comment]
It works only on platforms that support flash

**Comment by sourav86** [comment]
Then what is the alternate way to get clipboard functionality in angularjs

**Comment by asafdav** [comment]
That's a very good question, I never had the time to probe this. In case you find a solution, please report back I'd be happy to support it.
