### ISSUE TITLE
Flash overlay persisting between pages?

### ISSUE THREAD

**Issue by naps62** [asafdav/ng-clip#64]
I'm working on a Single Page Application written in Angular, where I'm trying to apply this module to a button

This seems to create an overlay with the flash object on top of the button. But when I click somewhere else to change the page (making the button disapear), the overlay stays there. It's still invisible, but I notice I can't over on anything where the button used to be

**Comment by bjaanes** [comment]
When using this with Bootstrap Modal, the flash overlay stays on the page after the modal is closed.

**Comment by JMourisca** [comment]
It seems that the same thing happens when using Bootstrap Tabs. :(
