### ISSUE TITLE
unminified version in `./dest`

### ISSUE THREAD

**Issue by anthonyettinger** [asafdav/ng-clip#69]
Can you provide an unminified version in `./dest`

**Comment by jgaya** [comment]
On Thu, May 28, 2015 at 4:39 PM, Anthony Ettinger <notifications@github.com>
wrote:

> unminified version in ./dest
>

done.


-- 
Saludos  Juan
/****************************************************************************************************************/
Caminar sobre el agua y desarrollar software sobre unos requisitos es
fácil, si ambos están congelados.
Existen 10 Clases De Personas Las Que Entienden Binario Y Las Que No
Para un optimista esta medio lleno, para un pesimista esta medio vacío,
para un ingeniero el vaso es el doble de grande de lo necesario
La Superstición trae mala suerte
