### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by levithomason** [asafdav/ng-clip#71]
It looks like this module has a good number of stars. There are also some great PRs open and valid issues.

Is it still being maintained, do you need some help knocking this stuff out?

**Comment by asafdav** [comment]
Any help would be highly appreciated, I'm planning to keep supporting this
package ?

**Comment by levithomason** [comment]
Cool, I can clean up some of the issues/PRs  if you add me.

**Comment by levithomason** [comment]
You can take a look at my contribs on ngToast if you want to see how I work. Also, TechnologyAdvice/tap-flux is a good repo to peruse.

**Comment by asafdav** [comment]
Done, I just sent you an email
