### ISSUE TITLE
Use clipboard.js instead?

### ISSUE THREAD

**Issue by dv336699** [asafdav/ng-clip#83]
Maybe we could use https://github.com/zenorocha/clipboard.js/ instead?

**Comment by asafdav** [comment]
Hi @diego-vieira this is a great idea, I created a first version using clipboard.js.

 I still need to update the README, cover all of the cases for backward compatibility and make sure we have a decent solution for Safari. 

In the meantime, it would be very helpful if you could check it out and let me know if it works for you.
you can see my work here at [clipboard-js](https://github.com/asafdav/ng-clip/tree/clipboard-js) branch

**Comment by dv336699** [comment]
@asafdav awesome, didn't notice that branch - sorry.
It's working fine for me on Chrome 45.0.2454.101 @ OSX.

Keep it up :)

**Comment by asafdav** [comment]
Hi, nothing to be sorry about, I created it thanks to you :)

**Comment by zenorocha** [comment]
;)

**Comment by asafdav** [comment]
Hi @zenorocha, did you try using it ?

**Comment by zenorocha** [comment]
Nope, why?
